spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/car_db
    username: normal
    password: 0000
  flyway:
    url: jdbc:postgresql://localhost:5432/car_db
    user: normal
    password: 0000
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    resilience4j:
      circuitbreaker:
        instances:
          carServiceCircuitBreaker:
            slidingWindowSize: 10
            failureRateThreshold: 50
            waitDurationInOpenState: 5s
            permittedNumberOfCallsInHalfOpenState: 3
            minimumNumberOfCalls: 5
            automaticTransitionFromOpenToHalfOpenEnabled: true
